{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "#importing Headers\n",
    "\n",
    "import pandas \n",
    "import csv\n",
    "import numpy \n",
    "import nltk\n",
    "import seaborn \n",
    "from nltk.tokenize import word_tokenize"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# loading the files \n",
    "\n",
    "file_train = 'train.csv'\n",
    "file_test = 'test.csv'\n",
    "file_valid = 'valid.csv'\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "training_mat = pandas.read_csv(file_train)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "testing_mat = pandas.read_csv(file_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "valid_mat = pandas.read_csv(file_valid,encoding='iso-8859-1')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Training Data set\n",
      "\n",
      "(10239, 14)\n",
      "     2635.json  FALSE  \\\n",
      "0   10540.json   True   \n",
      "1     324.json   True   \n",
      "2    1123.json  False   \n",
      "3    9028.json   True   \n",
      "4   12465.json   True   \n",
      "5    2342.json  False   \n",
      "6     153.json   True   \n",
      "7    5602.json   True   \n",
      "8    9741.json   True   \n",
      "9    7115.json   True   \n",
      "10   4148.json   True   \n",
      "11   5947.json  False   \n",
      "12   8616.json   True   \n",
      "13   8705.json  False   \n",
      "14  10683.json   True   \n",
      "\n",
      "   Says the Annies List political group supports third-trimester abortions on demand.  \\\n",
      "0   When did the decline of coal start? It started...                                   \n",
      "1   Hillary Clinton agrees with John McCain \"by vo...                                   \n",
      "2   Health care reform legislation is likely to ma...                                   \n",
      "3   The economic turnaround started at the end of ...                                   \n",
      "4   The Chicago Bears have had more starting quart...                                   \n",
      "5   Jim Dunnam has not lived in the district he re...                                   \n",
      "6   I'm the only person on this stage who has work...                                   \n",
      "7   However, it took $19.5 million in Oregon Lotte...                                   \n",
      "8   Says GOP primary opponents Glenn Grothman and ...                                   \n",
      "9   For the first time in history, the share of th...                                   \n",
      "10  Since 2000, nearly 12 million Americans have s...                                   \n",
      "11  When Mitt Romney was governor of Massachusetts...                                   \n",
      "12  The economy bled $24 billion due to the govern...                                   \n",
      "13  Most of the (Affordable Care Act) has already ...                                   \n",
      "14  In this last election in November, ... 63 perc...                                   \n",
      "\n",
      "                                     abortion            dwayne-bohac  \\\n",
      "0          energy,history,job-accomplishments          scott-surovell   \n",
      "1                              foreign-policy            barack-obama   \n",
      "2                                 health-care            blog-posting   \n",
      "3                                economy,jobs           charlie-crist   \n",
      "4                                   education               robin-vos   \n",
      "5                        candidates-biography  republican-party-texas   \n",
      "6                                      ethics            barack-obama   \n",
      "7                                        jobs          oregon-lottery   \n",
      "8   energy,message-machine-2014,voting-record           duey-stroebel   \n",
      "9                                   elections         robert-menendez   \n",
      "10    economy,jobs,new-hampshire-2012,poverty                bernie-s   \n",
      "11                       history,state-budget             mitt-romney   \n",
      "12         economy,federal-budget,health-care              doonesbury   \n",
      "13                                health-care             george-will   \n",
      "14                                  elections                bernie-s   \n",
      "\n",
      "          State representative          Texas    republican     0     1  \\\n",
      "0               State delegate       Virginia      democrat   0.0   0.0   \n",
      "1                    President       Illinois      democrat  70.0  71.0   \n",
      "2                          NaN            NaN          none   7.0  19.0   \n",
      "3                          NaN        Florida      democrat  15.0   9.0   \n",
      "4   Wisconsin Assembly speaker      Wisconsin    republican   0.0   3.0   \n",
      "5                          NaN          Texas    republican   3.0   1.0   \n",
      "6                    President       Illinois      democrat  70.0  71.0   \n",
      "7                          NaN            NaN  organization   0.0   0.0   \n",
      "8         State representative      Wisconsin    republican   0.0   0.0   \n",
      "9                 U.S. Senator     New Jersey      democrat   1.0   3.0   \n",
      "10                U.S. Senator        Vermont   independent  18.0  12.0   \n",
      "11             Former governor  Massachusetts    republican  34.0  32.0   \n",
      "12                         NaN            NaN          none   0.0   0.0   \n",
      "13                   Columnist       Maryland     columnist   7.0   6.0   \n",
      "14                U.S. Senator        Vermont   independent  18.0  12.0   \n",
      "\n",
      "      0.1    0.2   0.3                                  a mailer  \n",
      "0     1.0    1.0   0.0                           a floor speech.  \n",
      "1   160.0  163.0   9.0                                    Denver  \n",
      "2     3.0    5.0  44.0                            a news release  \n",
      "3    20.0   19.0   2.0                       an interview on CNN  \n",
      "4     2.0    5.0   1.0                 a an online opinion-piece  \n",
      "5     1.0    3.0   1.0                          a press release.  \n",
      "6   160.0  163.0   9.0  a Democratic debate in Philadelphia, Pa.  \n",
      "7     1.0    0.0   1.0                                a website   \n",
      "8     0.0    1.0   0.0                           an online video  \n",
      "9     1.0    3.0   0.0                                  a speech  \n",
      "10   22.0   41.0   0.0                                   a tweet  \n",
      "11   58.0   33.0  19.0                an interview with CBN News  \n",
      "12    2.0    4.0   0.0   a Doonesbury strip in the Sunday comics  \n",
      "13    3.0    5.0   1.0             comments on \"Fox News Sunday\"  \n",
      "14   22.0   41.0   0.0              a town hall in Austin, Texas  \n",
      "Testing Data set\n",
      "\n",
      "(1266, 14)\n",
      "    11972.json   TRUE  \\\n",
      "0   11685.json  False   \n",
      "1   11096.json  False   \n",
      "2    5209.json   True   \n",
      "3    9524.json  False   \n",
      "4    5962.json   True   \n",
      "5    7070.json   True   \n",
      "6    1046.json  False   \n",
      "7   12849.json   True   \n",
      "8   13270.json  False   \n",
      "9    6649.json  False   \n",
      "10   2508.json  False   \n",
      "11  11269.json  False   \n",
      "12  11200.json  False   \n",
      "13   8047.json   True   \n",
      "14   4888.json   True   \n",
      "\n",
      "   Building a wall on the U.S.-Mexico border will take literally years.  \\\n",
      "0   Wisconsin is on pace to double the number of l...                     \n",
      "1   Says John McCain has done nothing to help the ...                     \n",
      "2   Suzanne Bonamici supports a plan that will cut...                     \n",
      "3   When asked by a reporter whether hes at the ce...                     \n",
      "4   Over the past five years the federal governmen...                     \n",
      "5   Says that Tennessee law requires that schools ...                     \n",
      "6   Says Vice President Joe Biden \"admits that the...                     \n",
      "7   Donald Trump is against marriage equality. He ...                     \n",
      "8   We know that more than half of Hillary Clinton...                     \n",
      "9   We know there are more Democrats in Georgia th...                     \n",
      "10  PolitiFact Texas says Congressman Edwards atta...                     \n",
      "11         Denali is the Kenyan word for black power.                     \n",
      "12  Says 57 percent of federal spending goes to th...                     \n",
      "13       On residency requirements for public workers                     \n",
      "14  Says the unemployment rate for college graduat...                     \n",
      "\n",
      "                                          immigration  \\\n",
      "0                                                jobs   \n",
      "1                     military,veterans,voting-record   \n",
      "2   medicare,message-machine-2012,campaign-adverti...   \n",
      "3   campaign-finance,legal-issues,campaign-adverti...   \n",
      "4                  federal-budget,pensions,retirement   \n",
      "5     county-budget,county-government,education,taxes   \n",
      "6                                    economy,stimulus   \n",
      "7                          gays-and-lesbians,marriage   \n",
      "8                                      foreign-policy   \n",
      "9                                           elections   \n",
      "10                             ethics,message-machine   \n",
      "11                                        environment   \n",
      "12                    federal-budget,military,poverty   \n",
      "13           city-government,county-government,unions   \n",
      "14                                     education,jobs   \n",
      "\n",
      "                          rick-perry  \\\n",
      "0                  katrina-shankland   \n",
      "1                       donald-trump   \n",
      "2                      rob-cornilles   \n",
      "3   state-democratic-party-wisconsin   \n",
      "4                    brendan-doherty   \n",
      "5           stand-children-tennessee   \n",
      "6                       john-boehner   \n",
      "7               sean-patrick-maloney   \n",
      "8                         mike-pence   \n",
      "9                        mike-berlon   \n",
      "10                       bill-flores   \n",
      "11                       viral-image   \n",
      "12                    facebook-posts   \n",
      "13                       chris-abele   \n",
      "14                     rick-santorum   \n",
      "\n",
      "                                      Governor         Texas  republican  30  \\\n",
      "0                         State representative     Wisconsin    democrat   2   \n",
      "1                              President-Elect      New York  republican  63   \n",
      "2                                   consultant        Oregon  republican   1   \n",
      "3                                          NaN     Wisconsin    democrat   5   \n",
      "4                                          NaN  Rhode Island  republican   1   \n",
      "5   Child and education advocacy organization.     Tennessee        none   0   \n",
      "6      Speaker of the House of Representatives          Ohio  republican  13   \n",
      "7                        Congressman for NY-18      New York    democrat   0   \n",
      "8                                     Governor       Indiana  republican   8   \n",
      "9                                          NaN       Georgia    democrat   1   \n",
      "10                                 Businessman         Texas  republican   2   \n",
      "11                                         NaN           NaN        none   5   \n",
      "12                        Social media posting           NaN        none  14   \n",
      "13                              Philanthropist     Wisconsin        none   3   \n",
      "14                                         NaN  Pennsylvania  republican  12   \n",
      "\n",
      "    30.1  42  23  18                                 Radio interview  \n",
      "0      1   0   0   0                               a news conference  \n",
      "1    114  51  37  61                    comments on ABC's This Week.  \n",
      "2      1   3   1   1                                    a radio show  \n",
      "3      7   2   2   7                                     a web video  \n",
      "4      2   1   1   0                              a campaign website  \n",
      "5      0   0   0   0                          in a post on Facebook.  \n",
      "6     22  11   4   2                                a press release.  \n",
      "7      0   0   0   0  a speech at the Democratic National Convention  \n",
      "8     10  12   5   0                    comments on \"Meet the Press\"  \n",
      "9      0   0   0   0                                      an article  \n",
      "10     0   0   0   0                                        a TV ad.  \n",
      "11     5   0   3  15                     an image shared on Facebook  \n",
      "12    18  15  11  36                          a meme on social media  \n",
      "13     5   4   4   2                                        a letter  \n",
      "14    16  13   7   5                                        a speech  \n",
      "Valid Data set\n",
      "\n",
      "(1283, 14)\n",
      "    12134.json  FALSE We have less Americans working now than in the 70s.  \\\n",
      "0     238.json  False  When Obama was sworn into office, he DID NOT u...    \n",
      "1    7891.json  False  Says Having organizations parading as being so...    \n",
      "2    8169.json   True     Says nearly half of Oregons children are poor.    \n",
      "3     929.json   True  On attacks by Republicans that various program...    \n",
      "4    9416.json  False  Says when armed civilians stop mass shootings ...    \n",
      "5    6861.json   True  Says Tennessee is providing millions of dollar...    \n",
      "6    1122.json  False  The health care reform plan would set limits s...    \n",
      "7   13138.json   True  Says Donald Trump started his career back in 1...    \n",
      "8    1880.json   True  Bill White has a long history of trying to lim...    \n",
      "9   12803.json   True  John McCains chief economic adviser during the...    \n",
      "10   5409.json  False  Says 21,000 Wisconsin residents got jobs in 20...    \n",
      "11   7313.json   True  State revenue projections have missed the mark...    \n",
      "12   4809.json   True  The median income of a middle class family wen...    \n",
      "13   1671.json  False  Every citizen is entitled to the freedom of sp...    \n",
      "14   4348.json   True  Rick Perry has advocated abandoning Social Sec...    \n",
      "\n",
      "                              economy,jobs          vicky-hartzler  \\\n",
      "0         obama-birth-certificate,religion             chain-email   \n",
      "1          campaign-finance,congress,taxes         earl-blumenauer   \n",
      "2                                  poverty         jim-francesconi   \n",
      "3                         economy,stimulus            barack-obama   \n",
      "4                                     guns              jim-rubens   \n",
      "5                   education,state-budget              andy-berke   \n",
      "6                              health-care             club-growth   \n",
      "7   candidates-biography,diversity,housing         hillary-clinton   \n",
      "8                                 military  republican-party-texas   \n",
      "9                                  economy               tim-kaine   \n",
      "10         job-accomplishments,jobs,states       kathleen-vinehout   \n",
      "11                            state-budget            steve-henson   \n",
      "12               income,new-hampshire-2012               joe-biden   \n",
      "13                       gays-and-lesbians          david-dewhurst   \n",
      "14          medicaid,social-security,taxes        margaret-carlson   \n",
      "\n",
      "                              U.S. Representative              Missouri  \\\n",
      "0                                             NaN                   NaN   \n",
      "1                             U.S. representative                Oregon   \n",
      "2   Member of the State Board of Higher Education                Oregon   \n",
      "3                                       President              Illinois   \n",
      "4                            Small business owner         New Hampshire   \n",
      "5                        Lawyer and state senator             Tennessee   \n",
      "6                                             NaN                   NaN   \n",
      "7                          Presidential candidate              New York   \n",
      "8                                             NaN                 Texas   \n",
      "9                                    U.S. Senator              Virginia   \n",
      "10                                            NaN                   NaN   \n",
      "11                                  State Senator               Georgia   \n",
      "12                                   U.S. senator              Delaware   \n",
      "13                            Lieutenant governor                 Texas   \n",
      "14                                      Columnist  District of Columbia   \n",
      "\n",
      "    republican   1   0  1.1  0.1  0.2  \\\n",
      "0         none  11  43    8    5  105   \n",
      "1     democrat   0   1    1    1    0   \n",
      "2         none   0   1    1    1    0   \n",
      "3     democrat  70  71  160  163    9   \n",
      "4   republican   1   1    0    1    0   \n",
      "5     democrat   0   0    0    0    0   \n",
      "6         none   4   5    4    2    0   \n",
      "7     democrat  40  29   69   76    7   \n",
      "8   republican   3   1    1    3    1   \n",
      "9     democrat   8   3   15   15    0   \n",
      "10    democrat   1   1    1    1    0   \n",
      "11    democrat   0   0    1    0    0   \n",
      "12    democrat  11  10   21   16    4   \n",
      "13  republican   8   8   10    5    5   \n",
      "14        none   0   0    1    0    0   \n",
      "\n",
      "                         an interview with ABC17 News  \n",
      "0                                                 NaN  \n",
      "1                       a U.S. Ways and Means hearing  \n",
      "2                                  an opinion article  \n",
      "3                             interview with CBS News  \n",
      "4         in an interview at gun shop in Hudson, N.H.  \n",
      "5   a letter to state Senate education committee c...  \n",
      "6                                             a TV ad  \n",
      "7                       the first presidential debate  \n",
      "8                                           an e-mail  \n",
      "9   a speech at the Democratic National Convention...  \n",
      "10                                            remarks  \n",
      "11                                    a press release  \n",
      "12  speaking at New HampshireÛªs Plymouth State U...  \n",
      "13                                    a press release  \n",
      "14                                 a politics column.  \n"
     ]
    }
   ],
   "source": [
    "#printing data to check it is loaded\n",
    "def print_Data():\n",
    "    print(\"Training Data set\\n\")\n",
    "    print(training_mat.shape)\n",
    "    print(training_mat.head(15))\n",
    "    \n",
    "    print(\"Testing Data set\\n\")\n",
    "    print(testing_mat.shape)\n",
    "    print(testing_mat.head(15))\n",
    "    \n",
    "    print(\"Valid Data set\\n\")\n",
    "    print(valid_mat.shape)\n",
    "    print(valid_mat.head(15))\n",
    "    \n",
    "print_Data()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [],
   "source": [
    "#data quality check: cleaning\n",
    "def data_cleaning():\n",
    "    print(\"This function checks the null value in the data set\")\n",
    "    training_mat.isnull().sum()\n",
    "    training_mat.info()\n",
    "    \n",
    "    testing_mat.isnull().sum()\n",
    "    testing_mat.info()\n",
    "    \n",
    "    valid_mat.isnull().sum()\n",
    "    valid_mat.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
